### ISSUE TITLE
syntax error? maybe

### ISSUE THREAD

**Issue by mathew2005** [PikoCanFly/How-Sorry-Are-You-Quiz#1]
in the settings.py file , at the "INSTALLED_APPS" first there is no comma between the final two elements of the list. After i put a comma on mine, it says that quizapp is duplicated. either way i ultimatley removed 'quizapp' and only left 'sorryquiz.apps.SorryquizConfig' but now eventhough the server runs without an error appearing on my terminal, it doesn't display the quizzes i created in the admin panel.

**Comment by PikoCanFly** [comment]
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorryquiz.apps.SorryquizConfig'
]
```
I am not sure what you mean, all elements are separated by commas.

You can replace     'sorryquiz.apps.SorryquizConfig' with just sorryquiz , they both point to the sorryquiz app. 

When specifying the app in settings.py, you can use either the full Python path to the app's configuration class or just the app's name.

**Comment by mathew2005** [comment]
It was an another mistake that caused the quiz not to work. So forget about what I said earlier But yeah your right both are the same thing, they point to the app. But the only correction on the file in the settings.py, would be to only use one of the two pointers, your code uses both pointers. So it should look like

`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorryquiz.apps.SorryquizConfig'
]`

Or 

`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorryquiz'
]` 

But not both because, the terminal says duplicate and the code stops working.

**Comment by PikoCanFly** [comment]
If you check settings.py in my code you will find that the app is referenced once. At any case, I am glad your issue is resolved. 😊 

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorryquiz.apps.SorryquizConfig'
]
```
